#include "Ast.h"
#include "SymbolTable.h"
#include "Unit.h"
#include "Instruction.h"
#include "IRBuilder.h"
#include <string>
#include "Type.h"
#include <cstdio>
#include <sstream>

extern FILE *yyout;
int Node::counter = 0;
IRBuilder* Node::builder = nullptr;

Node::Node()
{
    seq = counter++;
}

void Node::backPatch(std::vector<BasicBlock**> &list, BasicBlock*target)
{
    for(auto &bb:list)
        *bb = target;
}

std::vector<BasicBlock**> Node::merge(std::vector<BasicBlock**> &list1, std::vector<BasicBlock**> &list2)
{
    std::vector<BasicBlock**> res(list1);
    res.insert(res.end(), list2.begin(), list2.end());
    return res;
}

void Ast::genCode(Unit *unit)   //根节点的中间代码生成
{
    IRBuilder *builder = new IRBuilder(unit);   //创建IRBuilder对象
    Node::setIRBuilder(builder);    //设置IRBuilder对象
    root->genCode();
}

void FunctionDef::genCode()
{
    fprintf(stderr,"进入FunctionDef::genCode\n");
    Unit *unit = builder->getUnit();    //获取当前编译单元
    fprintf(stderr, "已经获取当前编译单元\n");
    Function *func = new Function(unit, se);    //创建函数对象（参数：当前编译单元，符号表项）//此处构造函数已将其放入unit的funclist中
    fprintf(stderr, "已经创建函数对象\n");
    BasicBlock *entry = func->getEntry();//获取函数的入口基本块
    // set the insert point to the entry basicblock of this function.
    builder->setInsertBB(entry);//把所有定义语句都放到函数的入口基本块中
    fprintf(stderr, "已经将定义语句插入基本块\n");
    if (params != nullptr)
    {
        while(params != nullptr)
        {
            params->genCode();
            params = (DeclStmt*)(params->getNext());//遍历参数列表（params是DeclStmt，通过指针在.y文件中连成一个链表）
        }
    }   
    
    stmt->genCode();

    /**
     * Construct control flow graph. You need do set successors and predecessors for each basic block.
     * 构造控制流图。您需要为每个基本块设置后继和前驱。
     *
     * Todo
    */

 

}

void BinaryExpr::genCode()
{
    BasicBlock *bb = builder->getInsertBB();    //获取当前基本块
    //Function *func = bb->getParent();   //获取当前基本块所属的函数
    if (op == AND)
    {
        //BasicBlock *trueBB = new BasicBlock(func);  // if the result of lhs is true, jump to the trueBB.如果lhs的结果为true，跳转到trueBB
        expr1->genCode();
        //backPatch(expr1->trueList(), trueBB);
        //builder->setInsertBB(trueBB);               // set the insert point to the trueBB so that intructions generated by expr2 will be inserted into it.设置插入点为trueBB，以便expr2生成的指令会插入到其中
        expr2->genCode();
        //true_list = expr2->trueList();
        //false_list = merge(expr1->falseList(), expr2->falseList());
        Operand *src1=expr1->getOperand();
        Operand *src2=expr2->getOperand();
        Type *type1=src1->getType();
        Type *type2=src2->getType();

        fprintf(stderr, "观察type1%s\n",type1->toStr().c_str());
        fprintf(stderr, "观察type2%s\n",type2->toStr().c_str());
        fprintf(stderr, "dynamic_cast<IntType*>(type1)->getSize():%d\n",dynamic_cast<IntType*>(type1)->getSize());
        if(type1->isInt()&& dynamic_cast<IntType*>(type1)->getSize()==32)
        {
            fprintf(stderr, "expr1有变化\n");
            src1 = new Operand(new TemporarySymbolEntry(new IntType(1), SymbolTable::getLabel()));
            new CmpInstruction(CmpInstruction::NE, src1, expr1->getOperand(), new Operand(new ConstantSymbolEntry(0)), bb);
        }
        if(type2->isInt()&& dynamic_cast<IntType*>(type2)->getSize()==32)
        {
            fprintf(stderr, "expr2有变化\n");
            src2 = new Operand(new TemporarySymbolEntry(new IntType(1), SymbolTable::getLabel()));
            new CmpInstruction(CmpInstruction::NE, src2, expr2->getOperand(), new Operand(new ConstantSymbolEntry(0)), bb);
        }
        dst = new Operand(new TemporarySymbolEntry(new IntType(1), SymbolTable::getLabel()));
        new BinaryInstruction(BinaryInstruction::AND, dst, src1,src2, bb);

    }
    else if(op == OR)
    {
        // Todo
        //BasicBlock *falseBB = new BasicBlock(func);  // 如果lhs的结果为false，跳转到falseBB
        expr1->genCode();
        //backPatch(expr1->falseList(), falseBB);
        //builder->setInsertBB(falseBB);               // 设置插入点为falseBB，以便expr2生成的指令会插入到其中
        expr2->genCode();
        //true_list = merge(expr1->trueList(), expr2->trueList());
        //false_list = expr2->falseList();
        Operand *src1=expr1->getOperand();
        Operand *src2=expr2->getOperand();
        Type *type1=src1->getType();
        Type *type2=src2->getType();

        if(type1->isInt()&& dynamic_cast<IntType*>(type1)->getSize()==32)
        {
            src1 = new Operand(new TemporarySymbolEntry(new IntType(1), SymbolTable::getLabel()));
            new CmpInstruction(CmpInstruction::NE, src1, expr1->getOperand(), new Operand(new ConstantSymbolEntry(0)), bb);
        }
        if(type2->isInt()&& dynamic_cast<IntType*>(type2)->getSize()==32)
        {
            src2 = new Operand(new TemporarySymbolEntry(new IntType(1), SymbolTable::getLabel()));
            new CmpInstruction(CmpInstruction::NE, src2, expr2->getOperand(), new Operand(new ConstantSymbolEntry(0)), bb);
        }
        dst = new Operand(new TemporarySymbolEntry(new IntType(1), SymbolTable::getLabel()));
        new BinaryInstruction(BinaryInstruction::OR, dst, src1,src2, bb);

    }
    else if(op >= LESS && op <= NOTEQUAL)    //表示一系列运算符，用枚举值范围来区分//原本条件为op >= LESS && op <= GREATER，更改以适配所有的比较运算符
    {
        expr1->genCode();
        expr2->genCode();
        Operand *src1 = expr1->getOperand();    //获取操作数
        Operand *src2 = expr2->getOperand();
        int opcode;
        switch (op)
        {
        case LESS:
            opcode = CmpInstruction::L;
            break;
        case LESSOREQUAL:

            opcode = CmpInstruction::LE;
            break;
        case GREATER:
            opcode = CmpInstruction::G;
            break;
        case GREATEROREQUAL:
            opcode = CmpInstruction::GE;
            break;
        case EQUAL:
            opcode = CmpInstruction::E;
            break;
        case NOTEQUAL:
            opcode = CmpInstruction::NE;
            break;
        default:
            opcode = -1;
            break;
        }
        fprintf(stderr, "生成比较指令\n");
        dst = new Operand(new TemporarySymbolEntry(new IntType(1), SymbolTable::getLabel()));    //创建一个临时符号表项
        new CmpInstruction(opcode, dst, src1, src2, bb);    //生成比较指令
        fprintf(stderr, "COMthis->dst->getType()->toStr() = %s\n",this->dst->getType()->toStr().c_str());

        // Todo
        
    }
    else if(op >= ADD && op <= SUB)//加减法
    {
        expr1->genCode();
        expr2->genCode();
        Operand *src1 = expr1->getOperand();//获取操作数
        Operand *src2 = expr2->getOperand();
        int opcode;
        switch (op)
        {
        case ADD:
            opcode = BinaryInstruction::ADD;
            break;
        case SUB:
            opcode = BinaryInstruction::SUB;
            break;
        default:
            opcode = -1;
            break;
        }
        if(src1->getType()->isInt()&& dynamic_cast<IntType*>(src1->getType())->getSize()==1)
        {
            src1 = new Operand(new TemporarySymbolEntry(new IntType(32), SymbolTable::getLabel()));
            new ZextInstruction(src1, expr1->getOperand(), bb);
        }
        if(src2->getType()->isInt()&& dynamic_cast<IntType*>(src2->getType())->getSize()==1)
        {
            src2 = new Operand(new TemporarySymbolEntry(new IntType(32), SymbolTable::getLabel()));
            new ZextInstruction(src2, expr2->getOperand(), bb);
        }
        new BinaryInstruction(opcode, dst, src1, src2, bb);
    }
    else if(op == MUL || op == DIV || op == MOD)//乘除取模
    {
        expr1->genCode();
        expr2->genCode();
        Operand *src1 = expr1->getOperand();//获取操作数
        Operand *src2 = expr2->getOperand();
        int opcode;
        switch (op)
        {
        case MUL:
            opcode = BinaryInstruction::MUL;
            break;
        case DIV:
            opcode = BinaryInstruction::DIV;
            break;
        case MOD:
            opcode = BinaryInstruction::MOD;
            break;
        default:
            opcode = -1;
            break;
        }
        new BinaryInstruction(opcode, dst, src1, src2, bb);
    }
    else
    {
        // Todo
    }
}

void Constant::genCode()
{
    // we don't need to generate code.//不需要生成代码

}

void Id::genCode()
{
    fprintf(stderr, "进入Id::genCode\n");
    BasicBlock *bb = builder->getInsertBB();//获取当前基本块
    Operand *addr = dynamic_cast<IdentifierSymbolEntry*>(symbolEntry)->getAddr();//获取符号表项的地址
    new LoadInstruction(dst, addr, bb); //生成load指令
}

void IfStmt::genCode()//????原来的代码不全？？？
{
    //fprintf(stderr,"WJJIfStmt::genCode\n");
    BasicBlock *now_bb = builder->getInsertBB();
    Function *func;
    BasicBlock *then_bb, *end_bb;

    func = builder->getInsertBB()->getParent();
    then_bb = new BasicBlock(func);
    end_bb = new BasicBlock(func);

    cond->genCode();
    backPatch(cond->trueList(), then_bb);
    backPatch(cond->falseList(), end_bb);

    builder->setInsertBB(then_bb);
    thenStmt->genCode();
    BasicBlock *then_over_bb = builder->getInsertBB();//then块结束后的基本块
    //then_bb = builder->getInsertBB();
    new UncondBrInstruction(end_bb, then_over_bb);


    Type *Condtype=cond->getSymbolEntry()->getType();
    Operand *Condsrc=cond->getOperand();
    if(Condtype->isInt()&& dynamic_cast<IntType*>(Condtype)->getSize()==32)
    {
        Condsrc = new Operand(new TemporarySymbolEntry(new IntType(1), SymbolTable::getLabel()));
        new CmpInstruction(CmpInstruction::NE, Condsrc, cond->getOperand(), new Operand(new ConstantSymbolEntry(0)), now_bb);
    }

    new CondBrInstruction(then_bb, end_bb, Condsrc, now_bb);

    builder->setInsertBB(end_bb);
        
    now_bb->addSucc(then_bb);
    then_bb->addPred(now_bb);

    now_bb->addSucc(end_bb);
    end_bb->addPred(now_bb);

    then_bb->addSucc(end_bb);
    end_bb->addPred(then_bb);


}

void IfElseStmt::genCode()
{
    Function *func;
    BasicBlock *then_bb, *else_bb,*end_bb;
    BasicBlock *now_bb = builder->getInsertBB();

    func = builder->getInsertBB()->getParent();
    then_bb = new BasicBlock(func);
    else_bb = new BasicBlock(func);
    end_bb = new BasicBlock(func);
    cond->genCode();
    backPatch(cond->trueList(), then_bb);
    backPatch(cond->falseList(), else_bb);

    builder->setInsertBB(then_bb);
    thenStmt->genCode();
    BasicBlock *then_over_bb = builder->getInsertBB();
    new UncondBrInstruction(end_bb, then_over_bb);

    builder->setInsertBB(else_bb);
    elseStmt->genCode();
    BasicBlock *else_over_bb = builder->getInsertBB();
    new UncondBrInstruction(end_bb, else_over_bb);
    Operand *Condsrc=cond->getOperand();
    Type *Condtype=cond->getSymbolEntry()->getType();

    if(Condtype->isInt()&& dynamic_cast<IntType*>(Condtype)->getSize()==32)
    {
        Condsrc = new Operand(new TemporarySymbolEntry(new IntType(1), SymbolTable::getLabel()));
        new CmpInstruction(CmpInstruction::NE, Condsrc, cond->getOperand(), new Operand(new ConstantSymbolEntry(0)), now_bb);
    }

    new CondBrInstruction(then_bb, else_bb, Condsrc, now_bb);
    
    builder->setInsertBB(end_bb);


    now_bb->addSucc(then_bb);
    then_bb->addPred(now_bb);
    now_bb->addSucc(else_bb);
    else_bb->addPred(now_bb);
    then_bb->addSucc(end_bb);
    end_bb->addPred(then_bb);
    else_bb->addSucc(end_bb);
    end_bb->addPred(else_bb);
    

}

void CompoundStmt::genCode()
{
    // Todo
    fprintf(stderr,"进入CompoundStmt::genCode\n");
    stmt->genCode();
    fprintf(stderr,"CompoundStmt::genCodeOVER\n");

}

void SeqNode::genCode()
{
    // Todo
    fprintf(stderr,"进入SeqNode::genCode\n");
    stmt1->genCode();
    stmt2->genCode();
}

void DeclStmt::genCode()
{
    fprintf(stderr,"进入DeclStmt::genCode\n");
    // if(id == nullptr)
    // {
    //     fprintf(stderr,"id为空\n");
    //     return;
    // }

    //se 表示变量本身的符号表项，而 addr_se 表示指向该变量的指针的符号表项。
    //addr_se 的类型是 PointerType，它指向 se 所表示的变量的类型。
    IdentifierSymbolEntry *se=nullptr;
    if(id != nullptr)
    se = dynamic_cast<IdentifierSymbolEntry *>(id->getSymPtr());//当前变量的符号表项
     else if(array != nullptr)
    se = dynamic_cast<IdentifierSymbolEntry *>(array->getSymPtr());//当前变量的符号表项

    fprintf(stderr,"符号表项是se->isGlobal() = %d\n",se->isGlobal());
    fprintf(stderr,"符号表项是se->isLocal() = %d\n",se->isLocal());
    fprintf(stderr,"符号表项是se->isParam() = %d\n",se->isParam());
    if(se->isGlobal())//全局变量
    {
        // //不属于任何函数，虚空变量
        fprintf(stderr,"进入DeclStmt::genCode中全局变量的部分\n");
        Operand *addr;
        SymbolEntry *addr_se;//用于存储新生成的符号表项
        Type *type;
        type = new PointerType(se->getType());//创建一个指针类型
        addr_se = new IdentifierSymbolEntry(*se);//创建一个新的符号表项
        //addr_se = new TemporarySymbolEntry(type, SymbolTable::getLabel());//这个到底是干什么使的啊啊啊啊啊啊啊！！！！！！！！！！！
        addr_se->setType(type);//设置类型(变量的数据类型)
        GlobalVariable *global = new GlobalVariable(se);//创建一个新的全局变量
         
        fprintf(stderr, "全局变量的类型是%s\n",se->getType()->toStr().c_str());
        addr = new Operand(addr_se);//创建一个目标数
        fprintf(stderr, "全局变量的地址是%s\n",addr->toStr().c_str());
        se->setAddr(addr);//设置操作数的地址

        Unit *unit = builder->getUnit();//获取当前编译单元
        unit->insertGlobal(global);//将全局变量插入到编译单元的全局变量列表中

        if(expr != nullptr)//如果有初始化表达式//全局变量不用store指令，直接在编译阶段初始化
        {
            fprintf(stderr, "具有初始化表达式\n");
            expr->genCode();
            fprintf(stderr, "expr中间代码生成结束\n");
            //Operand *src = expr->getOperand();//获取操作数
            if(expr->CanBeCalculatedInt){
                ConstantSymbolEntry* src = new ConstantSymbolEntry(expr->getSymbolEntry()->getType(),expr->CalculatedInt);//此处只有int
                fprintf(stderr, "获取操作数结束, %s\n",src->toStr().c_str());
                se->setInitialValue(src->toStr().c_str()); // 设置初始值
                fprintf(stderr, "设置初始值结束\n");
            }
            else{//未实现浮点数！！！！！！！！！！！！！！

                fprintf(stderr, "LAB3中间代码生成报错:全局变量的赋值不为常数\n");
                exit(1);
            }
            
        }
        if(initValList != nullptr)//如果有初始化值列表
        {
            fprintf(stderr, "具有初始化值列表\n");
            initValList->genCode();
            int DIM=dynamic_cast<IntArrayType*>(se->getType())->getDim();//获取维度
            long unsigned int dim1 = dynamic_cast<IntArrayType*>(se->getType())->dimSize->at(0);//获取第一维
            
            fprintf(stderr,"开始设置数组初值\n");
            if(DIM==1)
                se->setInitialValue(initValList->Dim1ToIR(dim1).c_str()); // 设置初始值
            if(DIM==2)
            {
            long unsigned int dim2 = dynamic_cast<IntArrayType*>(se->getType())->dimSize->at(1);//获取第二维
            se->setInitialValue(initValList->Dim2ToIR(dim2,dim1).c_str()); // 设置初始值

            }
        }

    }
    else if(se->isLocal())//局部变量
    {
        fprintf(stderr,"进入DeclStmt::genCode中局部变量的部分\n");
        Function *func = builder->getInsertBB()->getParent();//获取当前基本块所属的函数（即局部变量所属位置）
        BasicBlock *entry = func->getEntry();
        Instruction *alloca;//指令应为alloca指令
        Operand *addr;  //操作数
        SymbolEntry *addr_se;   //符号表项
        Type *type;
        type = new PointerType(se->getType());
        addr_se = new TemporarySymbolEntry(type, SymbolTable::getLabel());  //创建一个新的临时符号表项
        addr = new Operand(addr_se);
        alloca = new AllocaInstruction(addr, se);                   // allocate space for local id in function stack.
        fprintf(stderr, "addr是%s\n",addr->toStr().c_str());
        fprintf(stderr, "addr_se是%s\n",addr_se->toStr().c_str());
        fprintf(stderr,"指令类型是%d\n",alloca->getInstType());
        entry->insertFront(alloca);                                 // allocate instructions should be inserted into the begin of the entry block.
        fprintf(stderr,"已将alloca指令插入到基本块的最前面\n");
        se->setAddr(addr);                                          // set the addr operand in symbol entry so that we can use it in subsequent code generation.
    
        if(expr != nullptr)
        {
            expr->genCode();
            Operand *src = expr->getOperand();
            new StoreInstruction(addr, src, builder->getInsertBB());
        }
    
    }
    else if(se->isParam())//新加入参数检查
    {
        fprintf(stderr,"进入DeclStmt::genCode中参数的部分\n");
        Function *func = builder->getInsertBB()->getParent();//获取当前基本块所属的函数（即参数所属位置）
        BasicBlock *entry = func->getEntry();//获取函数的入口基本块
        Instruction *alloca;
        Operand *addr;  //操作数
        SymbolEntry *addr_se;   //符号表项
        Type *type;
        type = new PointerType(se->getType());
        fprintf(stderr, "指针参数类型是%s\n",type->toStr().c_str());
        fprintf(stderr, "是%s\n",se->getType()->toStr().c_str());
        
        addr_se = new TemporarySymbolEntry(type, SymbolTable::getLabel());  //创建一个新的临时符号表项
        addr = new Operand(addr_se);
         
        alloca = new AllocaInstruction(addr, se);                   // allocate space for local id in function stack.
        entry->insertFront(alloca);
        se->setAddr(addr);
        if(expr != nullptr)
        {
            expr->genCode();
            Operand *src = expr->getOperand();
            new StoreInstruction(addr, src, entry);//store指令
        }
    }

    fprintf(stderr,"DeclStmt::genCode结束\n");
}

void ReturnStmt::genCode()
{
    if(this->getRetValue()==nullptr)
    {
        fprintf(stderr, "进入空ReturnStmt\n");
        Function *func = builder->getInsertBB()->getParent();
        BasicBlock *exit = func->getExit();
        new UncondBrInstruction(exit, builder->getInsertBB());
        builder->getInsertBB()->addSucc(exit);
        exit->addPred(builder->getInsertBB());
        return;
    }
    this->getRetValue()->genCode();
    Function *func = builder->getInsertBB()->getParent();
    Operand *retValue = this->getRetValue()->getOperand();
    //BasicBlock *exit = func->getExit();
    BasicBlock *bb = builder->getInsertBB();
    Operand *addr = func->getRetValue();
    
    new StoreInstruction(addr, retValue, bb);
    new UncondBrInstruction(func->getExit(), bb);
    builder->getInsertBB()->addSucc(func->getExit());
    func->getExit()->addPred(builder->getInsertBB());
    //new RetInstruction(this->getRetValue()->getOperand(), builder->getInsertBB());
}

void AssignStmt::genCode()
{
    fprintf(stderr, "进入AssignStmt::genCode\n");
    BasicBlock *bb = builder->getInsertBB();//获取当前基本块
    lval->genCode();//需要加吗？？？？？？？？？
    expr->genCode();////////////////////////////////////////////这个地方出现的问题
    fprintf(stderr, "expr递归结束\n");
    Operand *addr = dynamic_cast<IdentifierSymbolEntry*>(lval->getSymPtr())->getAddr();//获取地址
    fprintf(stderr, "lval是\n");
    Operand *src = expr->getOperand();
    /***
     * We haven't implemented array yet, the lval can only be ID. So we just store the result of the `expr` to the addr of the id.
     * If you want to implement array, you have to caculate the address first and then store the result into it.
     */
    new StoreInstruction(addr, src, bb);
    fprintf(stderr, "AssignStmt::genCode结束\n");
}

void Ast::typeCheck()
{
    SymbolEntry *se = identifiers->lookup("main");
    if(se == nullptr)
    {
        fprintf(stderr, "LAB3类型检查报错:主函数不存在\n");
        exit(1);
    }
    if(se->getType()->isFunc() == false)
    {
        fprintf(stderr, "LAB3类型检查报错:main不为函数名\n");
        exit(1);
    }
    if(root != nullptr)
        root->typeCheck();
}

void FunctionDef::typeCheck()
{
    fprintf(stderr,"FunctionDef::typeCheck\n");
    if(params != nullptr)//参数不为空
    {
        fprintf(stderr,"该函数不为空,开始检查params，params是\n");
         params->typeCheck();
    }
    stmt->typeCheck();

    // Todo
}

void BinaryExpr::typeCheck()
{
    fprintf(stderr,"BinaryExpr::typeCheck\n");
    expr1->typeCheck();
    expr2->typeCheck();
    if(op==DIV&&expr2->CanBeCalculatedInt&&expr2->CalculatedInt==0)
    {
        fprintf(stderr, "LAB3类型检查报错:除数为0\n");
        exit(1);
    }
     //fprintf(stderr,"检查：%d %d\n",expr1->CanBeCalculatedInt,expr2->CanBeCalculatedInt);
     //fprintf(stderr,"看看：%d %d\n",expr1->CalculatedInt,expr2->CalculatedInt);
    if(expr1->CanBeCalculatedInt&&expr2->CanBeCalculatedInt)
    {
        CanBeCalculatedInt = true;
        switch(op)
        {
            case ADD:
                CalculatedInt = expr1->CalculatedInt + expr2->CalculatedInt;
                break;
            case SUB:
                CalculatedInt = expr1->CalculatedInt - expr2->CalculatedInt;
                break;
            case MUL:
                CalculatedInt = expr1->CalculatedInt * expr2->CalculatedInt;
                break;
            case DIV:
                //fprintf(stderr,"进来了吗");
                if(expr2->CalculatedInt == 0)
                {
                    fprintf(stderr, "LAB3类型检查报错:除数为0\n");
                    exit(1);
                }
                CalculatedInt = expr1->CalculatedInt / expr2->CalculatedInt;
                break;
            case MOD:
                CalculatedInt = expr1->CalculatedInt % expr2->CalculatedInt;
                break;
            case AND:
                CalculatedInt = expr1->CalculatedInt && expr2->CalculatedInt;
                break;
            case OR:
                CalculatedInt = expr1->CalculatedInt || expr2->CalculatedInt;
                break;
            case LESS:
                CalculatedInt = expr1->CalculatedInt < expr2->CalculatedInt;
                break;
            case LESSOREQUAL:
                CalculatedInt = expr1->CalculatedInt <= expr2->CalculatedInt;
                break;
            case GREATER:
                CalculatedInt = expr1->CalculatedInt > expr2->CalculatedInt;
                break;
            case GREATEROREQUAL:
                CalculatedInt = expr1->CalculatedInt >= expr2->CalculatedInt;
                break;
            case EQUAL:
                CalculatedInt = expr1->CalculatedInt == expr2->CalculatedInt;
                break;
            case NOTEQUAL:
                CalculatedInt = expr1->CalculatedInt != expr2->CalculatedInt;
                break;
        }
    }
    // Todo
     // 获取 expr1 和 expr2 的类型
    Type* type1 = this->getExpr1()->getSymbolEntry()->getType();//要获取类型，首先要获取符号表项，然后获取类型
    Type* type2 = this->getExpr2()->getSymbolEntry()->getType();

    fprintf(stderr,"type1是%s\n",type1->toStr().c_str());
    fprintf(stderr,"type2是%s\n",type2->toStr().c_str());

     // 数值运算符要求操作数都是数值类型
    if (type1->isVoid() || type2->isVoid()) 
    {
        fprintf(stderr, "void参与运算\n");
        fprintf(stderr, "LAB3类型检查报错:运算数不是数值类型\n");
        exit(EXIT_FAILURE);
    }//void参与运算，不会报我写的报错
    else if(type1->isFunc() || type2->isFunc())
    {
        if(type1->isFunc()){
            // 获取函数的返回值类型
            //fprintf(stderr, "type1是函数类型\n");
            Type* returnType1 = dynamic_cast<FunctionType*>(type1)->getRetType();
            if(returnType1->isVoid())
            {
                fprintf(stderr, "LAB3类型检查报错:函数返回值void参与双目运算\n");
                exit(EXIT_FAILURE);
            }
        }
        if(type2->isFunc()){
            // 获取函数的返回值类型
            //fprintf(stderr, "type2是函数类型\n");
            Type* returnType2 = dynamic_cast<FunctionType*>(type2)->getRetType();
            if(returnType2->isVoid())
            {
                fprintf(stderr, "LAB3类型检查报错:函数返回值void参与双目运算\n");
                exit(EXIT_FAILURE);
            }
        }
        
    }
   
    // 检查操作数类型是否兼容   //目前没啥用
    switch (op) {
        case ADD:
        case SUB:
        case MUL:
        case DIV:
        case MOD:
        case AND:
        case OR:
            // // 逻辑运算符要求操作数都是整数类型？？？？？？？？？？是必须整数吗？？？
            // if (!type1->isInt() || !type2->isInt() || !type1->isFloat() || !type2->isFloat()) {
            //     fprintf(stderr, "LAB3类型检查报错:非整数参与逻辑运算\n");
            //     exit(EXIT_FAILURE);
            // }//需要检查吗？？？？？？？？？？？？？？？
            // break;
        case LESS:
        case LESSOREQUAL:
        case GREATER:
        case GREATEROREQUAL:
        case EQUAL:
        case NOTEQUAL:
            // 比较运算符要求操作数类型相同吗？？？？？？？
            if (type1 != type2) {
                fprintf(stderr, "LAB3类型检查报错:比较运算符两操作数类型不同\n");
                //exit(EXIT_FAILURE);
            }
            break;
        default:
            fprintf(stderr, "LAB3类型检查报错:未知运算符类型\n");
            exit(EXIT_FAILURE);
    }
    //不在typecheck中设置类型，而是在genCode中设置类型
   // 设置当前表达式的类型
    // if (op == AND || op == OR || op == LESS || op == LESSOREQUAL || op == GREATER || op == GREATEROREQUAL || op == EQUAL || op == NOTEQUAL) {
    //     this->symbolEntry->setType(TypeSystem::intType); // 使用整数类型表示布尔结果    //隐式转换
    // } else {
    //     this->symbolEntry->setType(type1); // 数值运算符的结果类型与操作数类型相同  //隐式转换未实现（float+int）
    // }

}
void UnaryExpr::typeCheck()//补充说明：单目运算符可以出现在任何地方！！！
{
    fprintf(stderr,"UnaryExpr::typeCheck\n");
    expr->typeCheck();
    Type* type = expr->getSymbolEntry()->getType();//获取表达式类型

    //如果表达式类型是void，报错
    if(type->isVoid())
    {
        fprintf(stderr, "LAB3类型检查报错:表达式类型为void\n");
        exit(EXIT_FAILURE);
    }
    else if(type->isFunc())
    {
            // 获取函数的返回值类型
            //fprintf(stderr, "type是函数类型\n");
            Type* returnType = dynamic_cast<FunctionType*>(type)->getRetType();//将type转换为其子类func类型，然后获取函数返回值的类型
            if(returnType->isVoid())
            {
                fprintf(stderr, "LAB3类型检查报错:函数返回值void参与单目运算\n");
                exit(EXIT_FAILURE);
            }
        
    }

    if(expr->CanBeCalculatedInt)//如果expr可以计算成一个整数，用于check除数为零
    {
        CanBeCalculatedInt = true;
        switch(op)
        {
            case POS:
                CalculatedInt = expr->CalculatedInt;
                break;
            case NEG:
                CalculatedInt = -expr->CalculatedInt;
                break;
            case NOT:
                CalculatedInt = !expr->CalculatedInt;
                break;
        }
    }

    //？？？？？？对吗？？？？
    // if (op == NOT) {
    //     this->symbolEntry->setType(TypeSystem::intType); // 使用整数类型表示布尔结果    //隐式转换
    // }
}

void Constant::typeCheck()
{
    //fprintf(stderr,"???\n");
    
    if(symbolEntry->getType()->isInt())
    {
        this->CanBeCalculatedInt = true;
        this->CalculatedInt = atoi(symbolEntry->toStr().c_str());
    }
    fprintf(stderr,"Constant::typeCheck\n");
    // Todo
}

void Id::typeCheck()
{
    fprintf(stderr,"Id::typeCheck\n");
    if(this->getSymbolEntry()->getType()->getConst())
    {
        this->CanBeCalculatedInt = true;
        this->CalculatedInt = dynamic_cast<IdentifierSymbolEntry*>(this->getSymbolEntry())->ConstantValue;
    }
    //fprintf(stderr,"多少？？%d\n",this->CanBeCalculatedInt);

    // Todo
}

void IfStmt::typeCheck()
{
    fprintf(stderr,"IfStmt::typeCheck\n");
    cond->typeCheck();
    thenStmt->typeCheck();
    // Todo
}

void IfElseStmt::typeCheck()
{
    fprintf(stderr,"IfElseStmt::typeCheck\n");
    cond->typeCheck();
    thenStmt->typeCheck();
    elseStmt->typeCheck();

    // Todo
}

void CompoundStmt::typeCheck()
{
    fprintf(stderr,"CompoundStmt::typeCheck\n");
    stmt->typeCheck();

    // Todo
}

void SeqNode::typeCheck()
{
    fprintf(stderr,"SeqNode::typeCheck\n");
    stmt1->typeCheck();
    stmt2->typeCheck();

    // Todo
}

void DeclStmt::typeCheck()
{
    fprintf(stderr,"DeclStmt::typeCheck\n");
    if(array != nullptr)
    {
        array->typeCheck();
        for(long unsigned int i=0;i<(array->arrayIndex->index.size());i++)
        {

            if(array->arrayIndex->index[i]->CanBeCalculatedInt==false)
            {
                fprintf(stderr, "LAB3类型检查报错:数组大小不为常数\n");
                exit(EXIT_FAILURE);
            }
            else
            {

                if(array->arrayIndex->index[i]->CalculatedInt<=0)
                {
                    fprintf(stderr, "LAB3类型检查报错:数组大小小于等于0\n");
                    exit(EXIT_FAILURE);
                }

                if(array->getSymbolEntry()->getType()->isIntArray())
                {
                    dynamic_cast<IntArrayType*>(array->getSymbolEntry()->getType())->dimSize->push_back(array->arrayIndex->index[i]->CalculatedInt);

                }
                if(array->getSymbolEntry()->getType()->isFloatArray())
                {
                    dynamic_cast<FloatArrayType*>(array->getSymbolEntry()->getType())->dimSize->push_back(array->arrayIndex->index[i]->CalculatedInt);
                }
            }
        }
    
        fprintf(stderr,"最后array的类型是%s\n",array->getSymbolEntry()->getType()->toStr().c_str());
    }
    if(id != nullptr)
        id->typeCheck();
    if(expr != nullptr)
        expr->typeCheck();

    if(initValList!=nullptr)
        initValList->typeCheck();
    if(id!=nullptr && expr!=nullptr
        &&id->getSymbolEntry()->getType()->getConst() 
        &&id->getSymbolEntry()->getType()-> isInt())//
    {
        fprintf(stderr,"进入了常量初始化\n");
        if(expr->CanBeCalculatedInt)
        {
            id->CanBeCalculatedInt = true;
            if(id->getSymbolEntry()==nullptr)
            {
                fprintf(stderr, "LAB3类型检查报错:>>>>>\n");
                exit(EXIT_FAILURE);
            }

            dynamic_cast<IdentifierSymbolEntry*>(id->getSymbolEntry())->ConstantValue = expr->CalculatedInt;
            id->CalculatedInt = expr->CalculatedInt;

            //id->setSymbolEntry(new ConstantSymbolEntry(TypeSystem::intType,expr->CalculatedInt));
         }
        else
        {
            fprintf(stderr, "LAB3类型检查报错:常量初始化失败\n");
            exit(EXIT_FAILURE);
        }
    
    
    }


    // Todo
}

void ReturnStmt::typeCheck()
{
    fprintf(stderr,"ReturnStmt::typeCheck\n");
    if(retValue != nullptr)
    retValue->typeCheck();

    // Todo
}

void AssignStmt::typeCheck()//检查左值是否可以被赋值，右值是否可以用来赋值
{
    fprintf(stderr,"AssignStmt::typeCheck\n");
    lval->typeCheck();
    expr->typeCheck();


    // 获取左值和右值的类型
    Type* lvalType = lval->getSymbolEntry()->getType();
    Type* exprType = expr->getSymbolEntry()->getType();
    
    // 检查左值是否为可赋值的类型（例如标识符）
    if (!lvalType->isInt() && !lvalType->isFloat() && !lvalType->isLongLong() && !lvalType->isIntArray() && !lvalType->isFloatArray()) {
        fprintf(stderr, "LAB3类型检查报错:左值不是可赋值的类型\n");
        exit(EXIT_FAILURE);
    }

    if(exprType->isVoid())//右值是void类型
    {
        fprintf(stderr, "LAB3类型检查报错:右值为void类型\n");
        exit(EXIT_FAILURE);
    }
    // 检查右值是否为函数类型
    else if (exprType->isFunc()) {
        // 获取函数的返回值类型
        Type* returnType = dynamic_cast<FunctionType*>(exprType)->getRetType();
        // 检查返回值是否为 void
        if (returnType->isVoid()) {
            fprintf(stderr, "LAB3类型检查报错:函数返回值为void，不能赋值\n");
            exit(EXIT_FAILURE);
        }
        // 将函数的返回值类型作为右值类型
        exprType = returnType;
    }
    // // 检查左值和右值的类型是否兼容
    // if (lvalType != exprType) {
    //     fprintf(stderr, "LAB3类型检查报错:左值和右值的类型不匹配\n");
    //     exit(EXIT_FAILURE);
    // }

    // Todo
}
void Array::typeCheck()
{
    fprintf(stderr,"Array::typeCheck\n");
    id->typeCheck();
    arrayIndex->typeCheck();
    fprintf(stderr,"Array::typeCheckOVER\n");
}
void ArrayIndex::typeCheck()
{
    fprintf(stderr,"ArrayIndex::typeCheck\n");
    for(auto i : index)
    {
        i->typeCheck();
    }
    fprintf(stderr,"ArrayIndex::typeCheckOVER\n");
}
void FuncCall::typeCheck()//检查形参和实参的类型、数量，是否匹配//函数未定义即调用的报错，在语法分析阶段实现
{
    fprintf(stderr,"FuncCall::typeCheck\n");
    for(auto i : args)//遍历参数列表进行递归检查
    {
        fprintf(stderr,"进入循环\n");
        i->typeCheck();
    }

    int size_real=args.size();//实参个数
    fprintf(stderr,"已算出实参个数：%d\n",size_real);
    //func是一个Id，其父类的SymbolEntry是一个IdentifierSymbolEntry，在调用IdentifierSymbolEntry的父类的getType函数，返回其类型为Func，
    fprintf(stderr,"func的类型是%s\n",func->getSymbolEntry()->getType()->toStr().c_str());
    //fprintf(stderr,"形参个数是%ld\n",func->getSymbolEntry()->getType()->getParamsType().size());
    int size_form=dynamic_cast<FunctionType*>(func->getSymbolEntry()->getType())->getParamsType().size();//形参个数
    fprintf(stderr,"已算出形参个数：%d\n",size_form);

    if(size_real!=size_form)//检查实参个数和形参个数是否匹配
    {
        fprintf(stderr, "LAB3类型检查报错:实参个数与形参个数不匹配\n");
        exit(EXIT_FAILURE);
    }
    else{//检查实参和形参的类型是否匹配

        for(int i=0;i<size_real;i++)
        {
            Type* type_real=args[i]->getSymbolEntry()->getType();
            Type* type_form=dynamic_cast<FunctionType*>(func->getSymbolEntry()->getType())->getParamsType()[i];
            bool int_longlong = (type_real->isInt() && type_form->isLongLong()) || (type_real->isLongLong() && type_form->isInt());
            if((type_real!=type_form)&&!int_longlong)
            {
                fprintf(stderr, "LAB3类型检查报错:实参与形参类型不匹配\n");
                exit(EXIT_FAILURE);
            }
        }
    }

}
void BreakStmt::typeCheck()
{
    fprintf(stderr,"BreakStmt::typeCheck\n");

}
void ContinueStmt::typeCheck()
{
    fprintf(stderr,"ContinueStmt::typeCheck\n");
}
void EmptyStmt::typeCheck()
{
    fprintf(stderr,"EmptyStmt::typeCheck\n");
}
void WhileStmt::typeCheck()
{
    fprintf(stderr,"WhileStmt::typeCheck\n");
    cond->typeCheck();
    body->typeCheck();
}

void Ast::output()
{
    fprintf(yyout, "program\n");
    if(root != nullptr)
        root->output(4);
}

void BinaryExpr::output(int level)
{
    std::string op_str;
    switch(op)
    {
        //枚举变量在这派上用场了，枚举所有可能的二元运算符
        case ADD:
            op_str = "add";
            break;
        case SUB:
            op_str = "sub";
            break;
        case MUL:
            op_str = "mul";
            break;
        case DIV:
            op_str = "div";
            break;
        case MOD:
            op_str = "mod";
            break;
        case AND:
            op_str = "and";
            break;
        case OR:
            op_str = "or";
            break;
        case LESS:
            op_str = "less";
            break;
        case LESSOREQUAL:
            op_str = "lessorequal";
            break;
        case GREATER:
            op_str = "greater";
            break;
        case GREATEROREQUAL:
            op_str = "greaterorequal";
            break;
        case EQUAL:
            op_str = "equal";
            break;
        case NOTEQUAL:
            op_str = "notequal";
            break;
    }
    fprintf(yyout, "%*cBinaryExpr\top: %s\n", level, ' ', op_str.c_str());
    expr1->output(level + 4);   //递归输出左右表达式
    expr2->output(level + 4);
}

void UnaryExpr::output(int level)
{
    std::string op_str;
    switch(op)
    {
        case POS:
            op_str = "pos";
            break;
        case NEG:
            op_str = "neg";
            break;
        case NOT:
            op_str = "not";
            break;
    }
    fprintf(yyout, "%*cUnaryExpr\top: %s\n", level, ' ', op_str.c_str());
    expr->output(level + 4);
   
}

void Constant::output(int level)
{
    std::string type, value;
    type = symbolEntry->getType()->toStr();
    value = symbolEntry->toStr();
    fprintf(yyout, "%*cIntegerLiteral\tvalue: %s\ttype: %s\n", level, ' ',
            value.c_str(), type.c_str());
}

void Id::output(int level)
{
    std::string name, type;
    int scope;
    name = symbolEntry->toStr();
    type = symbolEntry->getType()->toStr();
    scope = dynamic_cast<IdentifierSymbolEntry*>(symbolEntry)->getScope();
    fprintf(yyout, "%*cId\tname: %s\tscope: %d\ttype: %s\n", level, ' ',
            name.c_str(), scope, type.c_str());
}



void FuncCall::output(int level)    // 函数调用输出
{
    fprintf(yyout, "%*cFuncCall\tname: %s\n", level, ' ', func->getSymbolEntry()->toStr().c_str()); // 输出函数名
    for (auto arg : args)   // 遍历参数
    {
        arg->output(level + 4); // 输出参数
    }
}


void CompoundStmt::output(int level)
{
    fprintf(yyout, "%*cCompoundStmt\n", level, ' ');
    stmt->output(level + 4);
}

void SeqNode::output(int level)
{
    stmt1->output(level);
    stmt2->output(level);
}

void DeclStmt::output(int level)
{
    fprintf(yyout, "%*cDeclStmt\n", level, ' ');
    if(array != nullptr)
        array->output(level + 4);
    if(id != nullptr)
    id->output(level + 4);
    if(expr != nullptr)
        expr->output(level + 4);
    if(initValList != nullptr)
        initValList->output(level + 4);
}

void IfStmt::output(int level)
{
    fprintf(yyout, "%*cIfStmt\n", level, ' ');
    cond->output(level + 4);
    thenStmt->output(level + 4);
}

void IfElseStmt::output(int level)
{
    fprintf(yyout, "%*cIfElseStmt\n", level, ' ');
    cond->output(level + 4);
    thenStmt->output(level + 4);
    elseStmt->output(level + 4);
}

void ReturnStmt::output(int level)
{
    fprintf(yyout, "%*cReturnStmt\n", level, ' ');
    retValue->output(level + 4);
}

void AssignStmt::output(int level)
{
    fprintf(yyout, "%*cAssignStmt\n", level, ' ');
    lval->output(level + 4);
    expr->output(level + 4);
}

void FunctionDef::output(int level)
{
    std::string name, type;
    name = se->toStr(); // se是函数符号表项，toStr()函数返回函数名
    type = se->getType()->toStr();
    fprintf(yyout, "%*cFunctionDefine function name: %s, type: %s\n", level, ' ', 
            name.c_str(), type.c_str());
    
    // 输出参数列表
    fprintf(yyout, "%*cParameters:\n", level + 4, ' ');

    while(params != nullptr)//遍历参数列表
        {
            std::string paramName = params->getId()->getSymbolEntry()->toStr();   // 通过参数获取参数名(必须先从DeclStmt提取出Id，才能获取其符号表项，进而输出)
            std::string paramType = params->getId()->getSymbolEntry()->getType()->toStr();// 通过参数获取参数类型
            int paramScope = dynamic_cast<IdentifierSymbolEntry*>(params->getId()->getSymbolEntry())->getScope(); // 获取参数的作用域
            fprintf(yyout, "%*c%s: %s, scope: %d\n", level + 8, ' ', paramName.c_str(), paramType.c_str(), paramScope); //输出参数名和参数类型
            params = (DeclStmt*)(params->getNext());
        }


    // for (auto param : params) {
    //     std::string paramName = param->getSymbolEntry()->toStr();   // 通过参数获取参数名
    //     std::string paramType = param->getSymbolEntry()->getType()->toStr();// 通过参数获取参数类型
    //     int paramScope = dynamic_cast<IdentifierSymbolEntry*>(param->getSymbolEntry())->getScope(); // 获取参数的作用域
    //     fprintf(yyout, "%*c%s: %s, scope: %d\n", level + 8, ' ', paramName.c_str(), paramType.c_str(), paramScope); //输出参数名和参数类型
    //     //fprintf(yyout, "%*c%s: %s\n", level + 8, ' ', paramName.c_str(), paramType.c_str());
    // }
    //获取函数参数的作用域并输出


    //scope = dynamic_cast<IdentifierSymbolEntry*>(se)->getScope();//获取函数参数的作用域
    
    // 输出函数体
    stmt->output(level + 4);
}


void WhileStmt::output(int level)   // While语句输出
{
    fprintf(yyout, "%*cWhileStmt\n", level, ' ');   // 输出WhileStmt
    cond->output(level + 4);    // 输出条件
    body->output(level + 4);    // 输出循环体
}
void EmptyStmt::output(int level)   // 空语句输出
{
    fprintf(yyout, "%*cEmptyStmt\n", level, ' ');   // 输出EmptyStmt
}
void ExprStmt::output(int level)
{
    fprintf(yyout, "%*cExprStmt\n", level, ' ');
    expr->output(level + 4);
}

void Array::output(int level)
{
    fprintf(yyout, "%*cArray\n", level, ' ');
    id->output(level + 4);
    arrayIndex->output(level + 4);
    
}

void ArrayIndex::output(int level)
{
    fprintf(yyout, "%*cArrayIndex\n", level, ' ');
    int j=0;
    for(auto i : index)
    {
        fprintf(yyout, "%*cIndex", level + 4, ' ');
        fprintf(yyout, " %d:\n", j);
        i->output(level + 4);
        j++;
    }
}

void BreakStmt::output(int level)
{
    fprintf(yyout, "%*cBreakStmt\n", level, ' ');
}
void ContinueStmt::output(int level)
{
    fprintf(yyout, "%*cContinueStmt\n", level, ' ');
}

void Array::genCode()
{
}
void ArrayIndex::genCode()
{
}
void FuncCall::genCode()//！！！！！！记得做
{
    fprintf(stderr,"进入FuncCall::genCode\n");
    BasicBlock *bb = builder->getInsertBB(); // 获取当前基本块

    // 生成实参的中间代码
    std::vector<Operand *> argsOperands;//实参的操作数
    for (auto arg : args) {
        arg->genCode();
        Operand *argOperand = arg->getOperand();
        if(argOperand->getType()->isInt()&& dynamic_cast<IntType*>(argOperand->getType())->getSize()==1)
        {
            argOperand = new Operand(new TemporarySymbolEntry(new IntType(32), SymbolTable::getLabel()));
            new ZextInstruction(argOperand, arg->getOperand(), bb);
        }

        argsOperands.push_back(argOperand);//将实参的操作数加入到argsOperands中
    }

    // 尝试获取函数符号表项
    IdentifierSymbolEntry *funcSE = dynamic_cast<IdentifierSymbolEntry *>(func->getSymbolEntry());

    //如果是库函数怎么怎么地
    if(funcSE==nullptr)//如果在标识符符号表里没有找到函数，那么他一定是库函数
    {
        fprintf(stderr, "进入库函数\n");
        FunctionSymbolEntry *library_funcSE = dynamic_cast<FunctionSymbolEntry *>(func->getSymbolEntry());
        // 创建返回值操作数
        Operand *retOperand = nullptr;//初始化返回值操作数
        fprintf(stderr, "库函数的类型是%d\n",library_funcSE->getReturnType()->isVoid());
        if (!library_funcSE->getType()->isVoid()) {//如果函数返回值不是void
        retOperand = new Operand(new TemporarySymbolEntry(library_funcSE->getType(), SymbolTable::getLabel()));//为什么是临时符号表项？？？？？？
        }

        // 生成函数调用指令
        new CallInstruction(retOperand, library_funcSE, argsOperands, bb);

        // 设置返回值操作数
        if (retOperand != nullptr) {
            dst = retOperand;
        }

    }
    else{
         // 创建返回值操作数
        Operand *retOperand = nullptr;//初始化返回值操作数
        if (!funcSE->getType()->isVoid()) {//如果函数返回值不是void
        retOperand = new Operand(new TemporarySymbolEntry(funcSE->getType(), SymbolTable::getLabel()));//为什么是临时符号表项？？？？？？
    }

        // 生成函数调用指令
        new CallInstruction(retOperand, funcSE, argsOperands, bb);

        // 设置返回值操作数
        if (retOperand != nullptr) {
            dst = retOperand;
        }

    }

   
    
    
}
void BreakStmt::genCode()
{
    BasicBlock *top_while_end = builder->getInsertBB()->getParent()->while_end.back();
    new UncondBrInstruction(top_while_end, builder->getInsertBB());

    top_while_end->addPred(builder->getInsertBB());
    builder->getInsertBB()->addSucc(top_while_end);

}
void ContinueStmt::genCode()
{
    BasicBlock *top_while_cond = builder->getInsertBB()->getParent()->while_cond.back();
    new UncondBrInstruction(top_while_cond, builder->getInsertBB());
    top_while_cond->addPred(builder->getInsertBB());
    builder->getInsertBB()->addSucc(top_while_cond);


}
void EmptyStmt::genCode()
{
}
void WhileStmt::genCode()
{
    BasicBlock *now_bb = builder->getInsertBB();
    Function *func;
    BasicBlock *body_bb, *end_bb ,*cond_bb;

    func = builder->getInsertBB()->getParent();
    body_bb = new BasicBlock(func);
    end_bb = new BasicBlock(func);
    cond_bb = new BasicBlock(func);
    func->while_cond.push_back(cond_bb);
    func->while_end.push_back(end_bb);

    builder->setInsertBB(cond_bb);
    cond->genCode();
    cond_bb = builder->getInsertBB();
    backPatch(cond->trueList(), body_bb);
    backPatch(cond->falseList(), end_bb);
    Operand *cond_op = cond->getOperand();
    if(cond_op->getType()->isInt()&& dynamic_cast<IntType*>(cond_op->getType())->getSize()==32)
    {
        cond_op = new Operand(new TemporarySymbolEntry(new IntType(1), SymbolTable::getLabel()));
        new CmpInstruction(CmpInstruction::NE, cond_op, cond->getOperand(), new Operand(new ConstantSymbolEntry(0)), cond_bb);
    }
    new CondBrInstruction(body_bb, end_bb, cond_op, cond_bb);

    builder->setInsertBB(body_bb);
    body_bb->while_cond=cond_bb;
    body_bb->while_end=end_bb;
    body->genCode();
    BasicBlock *body_over_bb = builder->getInsertBB();
    new UncondBrInstruction(cond_bb, body_over_bb);
    new UncondBrInstruction(cond_bb, now_bb);
    builder->setInsertBB(end_bb);

    func->while_cond.pop_back();
    func->while_end.pop_back();

    now_bb->addSucc(cond_bb);
    cond_bb->addPred(now_bb);

    cond_bb->addSucc(body_bb);
    body_bb->addPred(cond_bb);

    cond_bb->addSucc(end_bb);
    end_bb->addPred(cond_bb);

    body_bb->addSucc(cond_bb);
    cond_bb->addPred(body_bb);

}

void UnaryExpr::genCode()
{
    BasicBlock *bb = builder->getInsertBB();
    //Function *func = bb->getParent();
    expr->genCode();
    Operand *src = expr->getOperand();
    switch(op)
    {
        case POS:
            dst = src;
            break;
        case NEG:
            if(src->getType()->isLongLong())
            {
                long long value = dynamic_cast<ConstantSymbolEntry*>(src->getSymbolEntry())->getLongLongValue();
                dst = new Operand(new ConstantSymbolEntry(src->getType(), -value));
                fprintf(stderr, "进入NEG,value是%lld\n",value); 

            }
            else
            {
                dst = new Operand(new TemporarySymbolEntry(src->getType(), SymbolTable::getLabel()));
                new BinaryInstruction(BinaryInstruction::SUB, dst, new Operand(new ConstantSymbolEntry(src->getType(),0)), src, bb);

            }


            break;
        case NOT:
            dst = new Operand(new TemporarySymbolEntry(new IntType(1), SymbolTable::getLabel()));
            Operand *ToBoolSrc=src;
            Type* Srctype = src->getType();
            fprintf(stderr, "进入NOT,src->getType()->toStr()是%s\n",src->getType()->toStr().c_str());
            if(Srctype->isInt()&& dynamic_cast<IntType*>(Srctype)->getSize()==32)
            {
                ToBoolSrc = new Operand(new TemporarySymbolEntry(new IntType(1), SymbolTable::getLabel()));
                new CmpInstruction(CmpInstruction::NE, ToBoolSrc, src, new Operand(new ConstantSymbolEntry(0)), bb);
            }
            new BinaryInstruction(BinaryInstruction::XOR, dst, ToBoolSrc, new Operand(new ConstantSymbolEntry(new IntType(1),1)), bb);
            break;
    }

}


void ExprStmt::typeCheck()//怎么藏在这里！！！！！！！函数调用语句（区分函数调用）是一个ExprStmt（从这里连上funccall的递归）
{
    expr->typeCheck();
}


void ExprStmt::genCode()
{
    expr->genCode();
}
//将一维数组的大小转换为IR代码，只能在typecheck后调用
std::string InitValList::Dim1ToIR(int dim1)
{
    std::ostringstream buffer;
    Type* type = initVal[0]->getSymbolEntry()->getType();

    buffer << " [";

    for(int i=0;i<dim1;i++)
    {
        fprintf(stderr,"%d",i);
        
        if(i!=0)
        {
            buffer << ",";
        }
        if(i>(int)initVal.size()-1)
        {
            buffer <<type->toStr() <<" "<<0;
            continue;

        }
        if(type->isInt()&&initVal[i]->CanBeCalculatedInt)
        {
            buffer <<type->toStr() <<" "<<initVal[i]->CalculatedInt;
        }
        // else if(type->isFloat()&& initVal[i]->CalculatedFloat)
        // {
        //     buffer << initVal[i]->CalculatedFloat;
        // }
        // else
        // {
        //     fprintf(stderr, "LAB3类型检查报错:数组初始化值不是整数\n");
        //     exit(EXIT_FAILURE);
        // }

    }
    buffer << "]";
    fprintf(stderr,"buffer.str()是%s\n",buffer.str().c_str());
    return buffer.str();
}

std::string InitValList::Dim2ToIR(int dim1, int dim2)
{
    std::ostringstream buffer;
    ExprNode* node= initVal[0];
    SymbolEntry *se=node->getSymbolEntry();
    Type *type;
        if(se!=nullptr)
        {
            type=se->getType();
        }
        else
        {

            node=dynamic_cast<InitValList*>(node)->initVal[0];
            type=node->getSymbolEntry()->getType();
        }
        buffer<<"[";
    int BasicI=0;//本来初始化列表的第一级索引
    for(int i=0;i<dim2;i++)
    {
        if(i!=0)
        {
            buffer << ",";
        }
        buffer<<"["<<dim1<<" x "<<type->toStr()<<"]";
        

       if(initVal[BasicI]->getSymbolEntry()==nullptr)
       {
            std::vector<ExprNode*> BasiclineInitVal=dynamic_cast<InitValList*>(initVal[BasicI])->initVal;
            InitValList *line=new InitValList(BasiclineInitVal);
            buffer<<line->Dim1ToIR(dim1);
            BasicI++;
            continue;
       }
       else
       {
        std::vector<ExprNode*> lineInitVal; 
        while(1)
        {
            if((int)lineInitVal.size()>=dim1||initVal[BasicI]->getSymbolEntry()==nullptr)
                break;
            lineInitVal.push_back(initVal[BasicI]);
            BasicI++;

        }
            InitValList *line=new InitValList(lineInitVal);
            buffer<<line->Dim1ToIR(dim1);
            continue;

       }

    }
    buffer<<"]";
    return buffer.str();
}

void InitValList::output(int level)
{
    fprintf(yyout, "%*cInitValList\n", level, ' ');
    for(auto i : initVal)
    {
        i->output(level + 4);
    }
}
void InitValList::typeCheck()
{
    fprintf(stderr,"InitValList::typeCheck\n");
    for(auto i : initVal)
    {
        i->typeCheck();
    }
}
void InitValList::genCode()
{
    for(auto i : initVal)
    {
        i->genCode();
    }
}