#include "Ast.h"
#include "SymbolTable.h"
#include "Unit.h"
#include "Instruction.h"
#include "IRBuilder.h"
#include <string>
#include "Type.h"
#include <cstdio>

extern FILE *yyout;
int Node::counter = 0;
IRBuilder* Node::builder = nullptr;

Node::Node()
{
    seq = counter++;
}

void Node::backPatch(std::vector<BasicBlock**> &list, BasicBlock*target)
{
    for(auto &bb:list)
        *bb = target;
}

std::vector<BasicBlock**> Node::merge(std::vector<BasicBlock**> &list1, std::vector<BasicBlock**> &list2)
{
    std::vector<BasicBlock**> res(list1);
    res.insert(res.end(), list2.begin(), list2.end());
    return res;
}

void Ast::genCode(Unit *unit)
{
    IRBuilder *builder = new IRBuilder(unit);
    Node::setIRBuilder(builder);
    root->genCode();
}

void FunctionDef::genCode()
{
    Unit *unit = builder->getUnit();
    Function *func = new Function(unit, se);
    BasicBlock *entry = func->getEntry();
    // set the insert point to the entry basicblock of this function.
    builder->setInsertBB(entry);

    stmt->genCode();

    /**
     * Construct control flow graph. You need do set successors and predecessors for each basic block.
     * Todo
    */
   
}

void BinaryExpr::genCode()
{
    BasicBlock *bb = builder->getInsertBB();
    Function *func = bb->getParent();
    if (op == AND)
    {
        BasicBlock *trueBB = new BasicBlock(func);  // if the result of lhs is true, jump to the trueBB.
        expr1->genCode();
        backPatch(expr1->trueList(), trueBB);
        builder->setInsertBB(trueBB);               // set the insert point to the trueBB so that intructions generated by expr2 will be inserted into it.
        expr2->genCode();
        true_list = expr2->trueList();
        false_list = merge(expr1->falseList(), expr2->falseList());
    }
    else if(op == OR)
    {
        // Todo
    }
    else if(op >= LESS && op <= GREATER)
    {
        // Todo
    }
    else if(op >= ADD && op <= SUB)
    {
        expr1->genCode();
        expr2->genCode();
        Operand *src1 = expr1->getOperand();
        Operand *src2 = expr2->getOperand();
        int opcode;
        switch (op)
        {
        case ADD:
            opcode = BinaryInstruction::ADD;
            break;
        case SUB:
            opcode = BinaryInstruction::SUB;
            break;
        default:
            opcode = -1;
            break;
        }
        new BinaryInstruction(opcode, dst, src1, src2, bb);
    }
}

void Constant::genCode()
{
    // we don't need to generate code.
}

void Id::genCode()
{
    BasicBlock *bb = builder->getInsertBB();
    Operand *addr = dynamic_cast<IdentifierSymbolEntry*>(symbolEntry)->getAddr();
    new LoadInstruction(dst, addr, bb);
}

void IfStmt::genCode()
{
    Function *func;
    BasicBlock *then_bb, *end_bb;

    func = builder->getInsertBB()->getParent();
    then_bb = new BasicBlock(func);
    end_bb = new BasicBlock(func);

    cond->genCode();
    backPatch(cond->trueList(), then_bb);
    backPatch(cond->falseList(), end_bb);

    builder->setInsertBB(then_bb);
    thenStmt->genCode();
    then_bb = builder->getInsertBB();
    new UncondBrInstruction(end_bb, then_bb);

    builder->setInsertBB(end_bb);
}

void IfElseStmt::genCode()
{
    // Todo
}

void CompoundStmt::genCode()
{
    // Todo
}

void SeqNode::genCode()
{
    // Todo
}

void DeclStmt::genCode()
{
    IdentifierSymbolEntry *se = dynamic_cast<IdentifierSymbolEntry *>(id->getSymPtr());
    if(se->isGlobal())
    {
        Operand *addr;
        SymbolEntry *addr_se;
        addr_se = new IdentifierSymbolEntry(*se);
        addr_se->setType(new PointerType(se->getType()));
        addr = new Operand(addr_se);
        se->setAddr(addr);
    }
    else if(se->isLocal())
    {
        Function *func = builder->getInsertBB()->getParent();
        BasicBlock *entry = func->getEntry();
        Instruction *alloca;
        Operand *addr;
        SymbolEntry *addr_se;
        Type *type;
        type = new PointerType(se->getType());
        addr_se = new TemporarySymbolEntry(type, SymbolTable::getLabel());
        addr = new Operand(addr_se);
        alloca = new AllocaInstruction(addr, se);                   // allocate space for local id in function stack.
        entry->insertFront(alloca);                                 // allocate instructions should be inserted into the begin of the entry block.
        se->setAddr(addr);                                          // set the addr operand in symbol entry so that we can use it in subsequent code generation.
    }
}

void ReturnStmt::genCode()
{
    // Todo
}

void AssignStmt::genCode()
{
    BasicBlock *bb = builder->getInsertBB();
    expr->genCode();
    Operand *addr = dynamic_cast<IdentifierSymbolEntry*>(lval->getSymPtr())->getAddr();
    Operand *src = expr->getOperand();
    /***
     * We haven't implemented array yet, the lval can only be ID. So we just store the result of the `expr` to the addr of the id.
     * If you want to implement array, you have to caculate the address first and then store the result into it.
     */
    new StoreInstruction(addr, src, bb);
}

void Ast::typeCheck()
{
    SymbolEntry *se = identifiers->lookup("main");
    if(se == nullptr)
    {
        fprintf(stderr, "LAB3类型检查报错:主函数不存在\n");
        exit(1);
    }
    if(se->getType()->isFunc() == false)
    {
        fprintf(stderr, "LAB3类型检查报错:main不为函数名\n");
        exit(1);
    }
    if(root != nullptr)
        root->typeCheck();
}

void FunctionDef::typeCheck()
{
    printf("FunctionDef::typeCheck\n");
    stmt->typeCheck();

    // Todo
}

void BinaryExpr::typeCheck()
{
    printf("BinaryExpr::typeCheck\n");
    expr1->typeCheck();
    expr2->typeCheck();
    // printf("检查：%d %d\n",expr1->CanBeCalculatedInt,expr2->CanBeCalculatedInt);
    // printf("看看：%d %d\n",expr1->CalculatedInt,expr2->CalculatedInt);
    if(expr1->CanBeCalculatedInt&&expr2->CanBeCalculatedInt)
    {
        CanBeCalculatedInt = true;
        switch(op)
        {
            case ADD:
                CalculatedInt = expr1->CalculatedInt + expr2->CalculatedInt;
                break;
            case SUB:
                CalculatedInt = expr1->CalculatedInt - expr2->CalculatedInt;
                break;
            case MUL:
                CalculatedInt = expr1->CalculatedInt * expr2->CalculatedInt;
                break;
            case DIV:
                //printf("进来了吗");
                if(expr2->CalculatedInt == 0)
                {
                    fprintf(stderr, "LAB3类型检查报错:除数为0\n");
                    exit(1);
                }
                CalculatedInt = expr1->CalculatedInt / expr2->CalculatedInt;
                break;
            case MOD:
                CalculatedInt = expr1->CalculatedInt % expr2->CalculatedInt;
                break;
            case AND:
                CalculatedInt = expr1->CalculatedInt && expr2->CalculatedInt;
                break;
            case OR:
                CalculatedInt = expr1->CalculatedInt || expr2->CalculatedInt;
                break;
            case LESS:
                CalculatedInt = expr1->CalculatedInt < expr2->CalculatedInt;
                break;
            case LESSOREQUAL:
                CalculatedInt = expr1->CalculatedInt <= expr2->CalculatedInt;
                break;
            case GREATER:
                CalculatedInt = expr1->CalculatedInt > expr2->CalculatedInt;
                break;
            case GREATEROREQUAL:
                CalculatedInt = expr1->CalculatedInt >= expr2->CalculatedInt;
                break;
            case EQUAL:
                CalculatedInt = expr1->CalculatedInt == expr2->CalculatedInt;
                break;
            case NOTEQUAL:
                CalculatedInt = expr1->CalculatedInt != expr2->CalculatedInt;
                break;
        }
    }
    // Todo
     // 获取 expr1 和 expr2 的类型
    Type* type1 = this->getExpr1()->getSymbolEntry()->getType();//要获取类型，首先要获取符号表项，然后获取类型
    Type* type2 = this->getExpr2()->getSymbolEntry()->getType();

     // 数值运算符要求操作数都是数值类型
    if (type1->isVoid() || type2->isVoid()) 
    {
        fprintf(stderr, "LAB3类型检查报错:运算数不是数值类型\n");
        //exit(EXIT_FAILURE);
    }//void参与运算，不会报我写的报错


    // 检查操作数类型是否兼容   //目前没啥用
    switch (op) {
        case ADD:
        case SUB:
        case MUL:
        case DIV:
        case MOD:
        case AND:
        case OR:
            // 逻辑运算符要求操作数都是整数类型？？？？？？？？？？是必须整数吗？？？
            if (!type1->isInt() || !type2->isInt() || !type1->isFloat() || !type2->isFloat()) {
                fprintf(stderr, "LAB3类型检查报错:非整数参与逻辑运算\n");
                exit(EXIT_FAILURE);
            }//需要检查吗？？？？？？？？？？？？？？？
            break;
        case LESS:
        case LESSOREQUAL:
        case GREATER:
        case GREATEROREQUAL:
        case EQUAL:
        case NOTEQUAL:
            // 比较运算符要求操作数类型相同吗？？？？？？？
            if (type1 != type2) {
                fprintf(stderr, "LAB3类型检查报错:比较运算符两操作数类型不同\n");
                //exit(EXIT_FAILURE);
            }
            break;
        default:
            fprintf(stderr, "LAB3类型检查报错:未知运算符类型\n");
            exit(EXIT_FAILURE);
    }

   // 设置当前表达式的类型
    if (op == AND || op == OR || op == LESS || op == LESSOREQUAL || op == GREATER || op == GREATEROREQUAL || op == EQUAL || op == NOTEQUAL) {
        this->symbolEntry->setType(TypeSystem::intType); // 使用整数类型表示布尔结果    //隐式转换
    } else {
        this->symbolEntry->setType(type1); // 数值运算符的结果类型与操作数类型相同  //隐式转换未实现（float+int）
    }

}
void UnaryExpr::typeCheck()//补充说明：单目运算符可以出现在任何地方！！！
{
    printf("UnaryExpr::typeCheck\n");
    expr->typeCheck();
    Type* type = expr->getSymbolEntry()->getType();//获取表达式类型
    printf("单目运算符后面的type是%s\n",type->toStr().c_str());
    printf("type是void吗%d\n",type->isVoid());
    if(type->isVoid())//如果表达式类型是void
    {
        fprintf(stderr, "LAB3类型检查报错:表达式类型为void\n");
        exit(EXIT_FAILURE);
    }
    if(expr->CanBeCalculatedInt)//如果expr可以计算成一个整数，用于check除数为零
    {
        CanBeCalculatedInt = true;
        switch(op)
        {
            case POS:
                CalculatedInt = expr->CalculatedInt;
                break;
            case NEG:
                CalculatedInt = -expr->CalculatedInt;
                break;
            case NOT:
                CalculatedInt = !expr->CalculatedInt;
                break;
        }
    }
}

void Constant::typeCheck()
{
    //printf("???\n");
    
    if(symbolEntry->getType()->isInt())
    {
        this->CanBeCalculatedInt = true;
        this->CalculatedInt = atoi(symbolEntry->toStr().c_str());
    }
    printf("Constant::typeCheck\n");
    // Todo
}

void Id::typeCheck()
{
    printf("Id::typeCheck\n");

    // Todo
}

void IfStmt::typeCheck()
{
    printf("IfStmt::typeCheck\n");
    cond->typeCheck();
    thenStmt->typeCheck();
    // Todo
}

void IfElseStmt::typeCheck()
{
    printf("IfElseStmt::typeCheck\n");
    cond->typeCheck();
    thenStmt->typeCheck();
    elseStmt->typeCheck();

    // Todo
}

void CompoundStmt::typeCheck()
{
    printf("CompoundStmt::typeCheck\n");
    stmt->typeCheck();

    // Todo
}

void SeqNode::typeCheck()
{
    printf("SeqNode::typeCheck\n");
    stmt1->typeCheck();
    stmt2->typeCheck();

    // Todo
}

void DeclStmt::typeCheck()
{
    printf("DeclStmt::typeCheck\n");
    if(array != nullptr)
        array->typeCheck();
    if(id != nullptr)
        id->typeCheck();
    if(expr != nullptr)
        expr->typeCheck();

    // Todo
}

void ReturnStmt::typeCheck()
{
    printf("ReturnStmt::typeCheck\n");
    retValue->typeCheck();

    // Todo
}

void AssignStmt::typeCheck()
{
    printf("AssignStmt::typeCheck\n");
    lval->typeCheck();
    expr->typeCheck();

    // Todo
}
void Array::typeCheck()
{
    printf("Array::typeCheck\n");
    id->typeCheck();
    arrayIndex->typeCheck();

}
void ArrayIndex::typeCheck()
{
    printf("ArrayIndex::typeCheck\n");
    for(auto i : index)
    {
        i->typeCheck();
    }
}
void FuncCall::typeCheck()//检查形参和实参的类型、数量，是否匹配//函数未定义即调用的报错，在语法分析阶段实现
{
    printf("FuncCall::typeCheck\n");
    for(auto i : args)//遍历参数列表进行递归检查//？？？？？？？？？？？？？？？？？？？？？？
    {
        printf("进入循环\n");
        i->typeCheck();
    }

    int size_real=args.size();//实参个数
    //func是一个Id，其父类的SymbolEntry是一个IdentifierSymbolEntry，在调用IdentifierSymbolEntry的父类的getType函数，返回其类型为Func，
    int size_form=dynamic_cast<FunctionType*>(func->getSymbolEntry()->getType())->getParamsType().size();//形参个数
    printf("已算出实参个数：%d\n",size_real);

    if(size_real!=size_form)//检查实参个数和形参个数是否匹配
    {
        fprintf(stderr, "LAB3类型检查报错:实参个数与形参个数不匹配\n");
        exit(EXIT_FAILURE);
    }
    else{//检查实参和形参的类型是否匹配

        for(int i=0;i<size_real;i++)
        {
            Type* type_real=args[i]->getSymbolEntry()->getType();
            Type* type_form=dynamic_cast<FunctionType*>(func->getSymbolEntry()->getType())->getParamsType()[i];
            if(type_real!=type_form)
            {
                fprintf(stderr, "LAB3类型检查报错:实参与形参类型不匹配\n");
                exit(EXIT_FAILURE);
            }
        }
    }

}
void BreakStmt::typeCheck()
{
    printf("BreakStmt::typeCheck\n");

}
void ContinueStmt::typeCheck()
{
    printf("ContinueStmt::typeCheck\n");
}
void EmptyStmt::typeCheck()
{
    printf("EmptyStmt::typeCheck\n");
}
void WhileStmt::typeCheck()
{
    printf("WhileStmt::typeCheck\n");
    cond->typeCheck();
    body->typeCheck();
}

void Ast::output()
{
    fprintf(yyout, "program\n");
    if(root != nullptr)
        root->output(4);
}

void BinaryExpr::output(int level)
{
    std::string op_str;
    switch(op)
    {
        //枚举变量在这派上用场了，枚举所有可能的二元运算符
        case ADD:
            op_str = "add";
            break;
        case SUB:
            op_str = "sub";
            break;
        case MUL:
            op_str = "mul";
            break;
        case DIV:
            op_str = "div";
            break;
        case MOD:
            op_str = "mod";
            break;
        case AND:
            op_str = "and";
            break;
        case OR:
            op_str = "or";
            break;
        case LESS:
            op_str = "less";
            break;
        case LESSOREQUAL:
            op_str = "lessorequal";
            break;
        case GREATER:
            op_str = "greater";
            break;
        case GREATEROREQUAL:
            op_str = "greaterorequal";
            break;
        case EQUAL:
            op_str = "equal";
            break;
        case NOTEQUAL:
            op_str = "notequal";
            break;
    }
    fprintf(yyout, "%*cBinaryExpr\top: %s\n", level, ' ', op_str.c_str());
    expr1->output(level + 4);   //递归输出左右表达式
    expr2->output(level + 4);
}

void UnaryExpr::output(int level)
{
    std::string op_str;
    switch(op)
    {
        case POS:
            op_str = "pos";
            break;
        case NEG:
            op_str = "neg";
            break;
        case NOT:
            op_str = "not";
            break;
    }
    fprintf(yyout, "%*cUnaryExpr\top: %s\n", level, ' ', op_str.c_str());
    expr->output(level + 4);
   
}

void Constant::output(int level)
{
    std::string type, value;
    type = symbolEntry->getType()->toStr();
    value = symbolEntry->toStr();
    fprintf(yyout, "%*cIntegerLiteral\tvalue: %s\ttype: %s\n", level, ' ',
            value.c_str(), type.c_str());
}

void Id::output(int level)
{
    std::string name, type;
    int scope;
    name = symbolEntry->toStr();
    type = symbolEntry->getType()->toStr();
    scope = dynamic_cast<IdentifierSymbolEntry*>(symbolEntry)->getScope();
    fprintf(yyout, "%*cId\tname: %s\tscope: %d\ttype: %s\n", level, ' ',
            name.c_str(), scope, type.c_str());
}



void FuncCall::output(int level)    // 函数调用输出
{
    fprintf(yyout, "%*cFuncCall\tname: %s\n", level, ' ', func->getSymbolEntry()->toStr().c_str()); // 输出函数名
    for (auto arg : args)   // 遍历参数
    {
        arg->output(level + 4); // 输出参数
    }
}


void CompoundStmt::output(int level)
{
    fprintf(yyout, "%*cCompoundStmt\n", level, ' ');
    stmt->output(level + 4);
}

void SeqNode::output(int level)
{
    stmt1->output(level);
    stmt2->output(level);
}

void DeclStmt::output(int level)
{
    fprintf(yyout, "%*cDeclStmt\n", level, ' ');
    if(array != nullptr)
        array->output(level + 4);
    if(id != nullptr)
    id->output(level + 4);
    if(expr != nullptr)
        expr->output(level + 4);
    if(initValList != nullptr)
        initValList->output(level + 4);
}

void IfStmt::output(int level)
{
    fprintf(yyout, "%*cIfStmt\n", level, ' ');
    cond->output(level + 4);
    thenStmt->output(level + 4);
}

void IfElseStmt::output(int level)
{
    fprintf(yyout, "%*cIfElseStmt\n", level, ' ');
    cond->output(level + 4);
    thenStmt->output(level + 4);
    elseStmt->output(level + 4);
}

void ReturnStmt::output(int level)
{
    fprintf(yyout, "%*cReturnStmt\n", level, ' ');
    retValue->output(level + 4);
}

void AssignStmt::output(int level)
{
    fprintf(yyout, "%*cAssignStmt\n", level, ' ');
    lval->output(level + 4);
    expr->output(level + 4);
}

void FunctionDef::output(int level)
{
    std::string name, type;
    name = se->toStr(); // se是函数符号表项，toStr()函数返回函数名
    type = se->getType()->toStr();
    fprintf(yyout, "%*cFunctionDefine function name: %s, type: %s\n", level, ' ', 
            name.c_str(), type.c_str());
    
    // 输出参数列表
    fprintf(yyout, "%*cParameters:\n", level + 4, ' ');

    while(params != nullptr)//遍历参数列表
        {
            std::string paramName = params->getId()->getSymbolEntry()->toStr();   // 通过参数获取参数名(必须先从DeclStmt提取出Id，才能获取其符号表项，进而输出)
            std::string paramType = params->getId()->getSymbolEntry()->getType()->toStr();// 通过参数获取参数类型
            int paramScope = dynamic_cast<IdentifierSymbolEntry*>(params->getId()->getSymbolEntry())->getScope(); // 获取参数的作用域
            fprintf(yyout, "%*c%s: %s, scope: %d\n", level + 8, ' ', paramName.c_str(), paramType.c_str(), paramScope); //输出参数名和参数类型
            params = (DeclStmt*)(params->getNext());
        }


    // for (auto param : params) {
    //     std::string paramName = param->getSymbolEntry()->toStr();   // 通过参数获取参数名
    //     std::string paramType = param->getSymbolEntry()->getType()->toStr();// 通过参数获取参数类型
    //     int paramScope = dynamic_cast<IdentifierSymbolEntry*>(param->getSymbolEntry())->getScope(); // 获取参数的作用域
    //     fprintf(yyout, "%*c%s: %s, scope: %d\n", level + 8, ' ', paramName.c_str(), paramType.c_str(), paramScope); //输出参数名和参数类型
    //     //fprintf(yyout, "%*c%s: %s\n", level + 8, ' ', paramName.c_str(), paramType.c_str());
    // }
    //获取函数参数的作用域并输出


    //scope = dynamic_cast<IdentifierSymbolEntry*>(se)->getScope();//获取函数参数的作用域
    
    // 输出函数体
    stmt->output(level + 4);
}


void WhileStmt::output(int level)   // While语句输出
{
    fprintf(yyout, "%*cWhileStmt\n", level, ' ');   // 输出WhileStmt
    cond->output(level + 4);    // 输出条件
    body->output(level + 4);    // 输出循环体
}
void EmptyStmt::output(int level)   // 空语句输出
{
    fprintf(yyout, "%*cEmptyStmt\n", level, ' ');   // 输出EmptyStmt
}
void ExprStmt::output(int level)
{
    fprintf(yyout, "%*cExprStmt\n", level, ' ');
    expr->output(level + 4);
}

void Array::output(int level)
{
    fprintf(yyout, "%*cArray\n", level, ' ');
    id->output(level + 4);
    arrayIndex->output(level + 4);
    
}

void ArrayIndex::output(int level)
{
    fprintf(yyout, "%*cArrayIndex\n", level, ' ');
    int j=0;
    for(auto i : index)
    {
        fprintf(yyout, "%*cIndex", level + 4, ' ');
        fprintf(yyout, " %d:\n", j);
        i->output(level + 4);
        j++;
    }
}

void BreakStmt::output(int level)
{
    fprintf(yyout, "%*cBreakStmt\n", level, ' ');
}
void ContinueStmt::output(int level)
{
    fprintf(yyout, "%*cContinueStmt\n", level, ' ');
}

void Array::genCode()
{
}
void ArrayIndex::genCode()
{
}
void FuncCall::genCode()
{
}
void BreakStmt::genCode()
{
}
void ContinueStmt::genCode()
{
}
void EmptyStmt::genCode()
{
}
void WhileStmt::genCode()
{
}

void UnaryExpr::genCode()
{
}
void ExprStmt::typeCheck()
{
}
void ExprStmt::genCode()
{
}

void InitValList::output(int level)
{
    fprintf(yyout, "%*cInitValList\n", level, ' ');
    for(auto i : initVal)
    {
        i->output(level + 4);
    }
}
void InitValList::typeCheck()
{
    for(auto i : initVal)
    {
        i->typeCheck();
    }
}
void InitValList::genCode()
{
    for(auto i : initVal)
    {
        i->genCode();
    }
}